from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(185, 0, 606, 796))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth()
        )
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setStyleSheet('font: 16pt "Calibri";')
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(500, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(40, 30, 40, 30)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.courseNameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.courseNameLineEdit.setMinimumSize(QtCore.QSize(500, 30))
        self.courseNameLineEdit.setObjectName("courseNameLineEdit")
        self.verticalLayout_2.addWidget(self.courseNameLineEdit)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.descTextEdit = QtWidgets.QTextEdit(self.frame)
        self.descTextEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.descTextEdit.setObjectName("descTextEdit")
        self.verticalLayout_2.addWidget(self.descTextEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.durationLineEdit = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.durationLineEdit.sizePolicy().hasHeightForWidth()
        )
        self.durationLineEdit.setSizePolicy(sizePolicy)
        self.durationLineEdit.setMinimumSize(QtCore.QSize(100, 30))
        self.durationLineEdit.setMaximumSize(QtCore.QSize(80, 40))
        self.durationLineEdit.setObjectName("durationLineEdit")
        self.durationLineEdit.setValidator(QtGui.QIntValidator(1, 9, self.frame))
        self.horizontalLayout.addWidget(self.durationLineEdit)
        self.durationComboBox = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(
            self.durationComboBox.sizePolicy().hasHeightForWidth()
        )
        self.durationComboBox.setSizePolicy(sizePolicy)
        self.durationComboBox.setMinimumSize(QtCore.QSize(100, 30))
        self.durationComboBox.setMaximumSize(QtCore.QSize(200, 40))
        self.durationComboBox.setSizeIncrement(QtCore.QSize(0, 40))
        self.durationComboBox.setBaseSize(QtCore.QSize(40, 40))
        self.durationComboBox.setSizeAdjustPolicy(
            QtWidgets.QComboBox.AdjustToContentsOnFirstShow
        )
        self.durationComboBox.setIconSize(QtCore.QSize(64, 64))
        self.durationComboBox.setObjectName("durationComboBox")
        self.durationComboBox.addItem("")
        self.durationComboBox.addItem("")
        self.durationComboBox.addItem("")
        self.horizontalLayout.addWidget(self.durationComboBox)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 8)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.feesLineEdit = QtWidgets.QLineEdit(self.frame)
        self.feesLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.feesLineEdit.setMaxLength(9)
        self.feesLineEdit.setObjectName("feesLineEdit")
        self.feesLineEdit.setValidator(QtGui.QIntValidator(1, 9999, self.frame))
        self.verticalLayout_2.addWidget(self.feesLineEdit)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.difficultyComboBox = QtWidgets.QComboBox(self.frame)
        self.difficultyComboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.difficultyComboBox.setAutoFillBackground(False)
        self.difficultyComboBox.setEditable(False)
        self.difficultyComboBox.setMaxCount(3)
        self.difficultyComboBox.setIconSize(QtCore.QSize(64, 64))
        self.difficultyComboBox.setObjectName("difficultyComboBox")
        self.difficultyComboBox.addItem("")
        self.difficultyComboBox.addItem("")
        self.difficultyComboBox.addItem("")
        self.verticalLayout_2.addWidget(self.difficultyComboBox)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.linkLineEdit = QtWidgets.QLineEdit(self.frame)
        self.linkLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.linkLineEdit.setObjectName("linkLineEdit")
        self.verticalLayout_2.addWidget(self.linkLineEdit)
        self.addCoursePushButton = QtWidgets.QPushButton(self.frame)
        self.addCoursePushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.addCoursePushButton.setObjectName("addCoursePushButton")
        self.verticalLayout_2.addWidget(self.addCoursePushButton)
        self.verticalLayout_3.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.difficultyComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Course"))
        self.label.setText(_translate("MainWindow", "Course Name"))
        self.label_2.setText(_translate("MainWindow", "Description"))
        self.label_3.setText(_translate("MainWindow", "Duration"))
        self.durationComboBox.setItemText(0, _translate("MainWindow", "Weeks"))
        self.durationComboBox.setItemText(1, _translate("MainWindow", "Months"))
        self.durationComboBox.setItemText(2, _translate("MainWindow", "Years"))
        self.label_4.setText(_translate("MainWindow", "Fees"))
        self.label_5.setText(_translate("MainWindow", "Difficulty"))
        self.difficultyComboBox.setCurrentText(_translate("MainWindow", "Beginner"))
        self.difficultyComboBox.setItemText(0, _translate("MainWindow", "Beginner"))
        self.difficultyComboBox.setItemText(1, _translate("MainWindow", "Intermediate"))
        self.difficultyComboBox.setItemText(2, _translate("MainWindow", "Advanced"))
        self.label_6.setText(_translate("MainWindow", "Course Link"))
        self.addCoursePushButton.setText(_translate("MainWindow", "Add Course"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
