from PyQt5 import QtCore, QtGui, QtWidgets

difficulties = ["Beginner", "Intermediate", "Advanced"]


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centralwidget.sizePolicy().hasHeightForWidth()
        )
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 965, 1222))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth()
        )
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(20, 20, 30, 20)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_4.setSpacing(30)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.courseNameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(72)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.courseNameLabel.setFont(font)
        self.courseNameLabel.setTextFormat(QtCore.Qt.AutoText)
        self.courseNameLabel.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft
        )
        self.courseNameLabel.setWordWrap(True)
        self.courseNameLabel.setObjectName("courseNameLabel")
        self.verticalLayout_4.addWidget(self.courseNameLabel)
        self.row_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.row_2.setObjectName("row_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.row_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.instructorLabel = QtWidgets.QLabel(self.row_2)
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(36)
        self.instructorLabel.setFont(font)
        self.instructorLabel.setObjectName("instructorLabel")
        self.horizontalLayout.addWidget(self.instructorLabel)
        self.purchaseButton = QtWidgets.QPushButton(self.row_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.purchaseButton.sizePolicy().hasHeightForWidth()
        )
        self.purchaseButton.setSizePolicy(sizePolicy)
        self.purchaseButton.setMinimumSize(QtCore.QSize(250, 100))
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(28)
        self.purchaseButton.setFont(font)
        self.purchaseButton.setObjectName("purchaseButton")
        self.horizontalLayout.addWidget(self.purchaseButton)
        self.verticalLayout_4.addWidget(self.row_2)
        self.row_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.row_3.sizePolicy().hasHeightForWidth())
        self.row_3.setSizePolicy(sizePolicy)
        self.row_3.setObjectName("row_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.row_3)
        self.horizontalLayout_2.setContentsMargins(25, 25, 25, 25)
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.descLabel = QtWidgets.QLabel(self.row_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descLabel.sizePolicy().hasHeightForWidth())
        self.descLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(24)
        self.descLabel.setFont(font)
        self.descLabel.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.descLabel.setWordWrap(True)
        self.descLabel.setIndent(0)
        self.descLabel.setObjectName("descLabel")
        self.horizontalLayout_2.addWidget(self.descLabel)
        self.line = QtWidgets.QFrame(self.row_3)
        self.line.setMinimumSize(QtCore.QSize(10, 0))
        self.line.setMaximumSize(QtCore.QSize(10, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.vertical = QtWidgets.QWidget(self.row_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vertical.sizePolicy().hasHeightForWidth())
        self.vertical.setSizePolicy(sizePolicy)
        self.vertical.setObjectName("vertical")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.vertical)
        self.verticalLayout_3.setContentsMargins(-1, 12, 20, -1)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.vertical)
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.diffLabel = QtWidgets.QLabel(self.vertical)
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(28)
        self.diffLabel.setFont(font)
        self.diffLabel.setObjectName("diffLabel")
        self.verticalLayout_3.addWidget(self.diffLabel)
        spacerItem = QtWidgets.QSpacerItem(
            20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed
        )
        self.verticalLayout_3.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.vertical)
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.durationLabel = QtWidgets.QLabel(self.vertical)
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(28)
        self.durationLabel.setFont(font)
        self.durationLabel.setObjectName("durationLabel")
        self.verticalLayout_3.addWidget(self.durationLabel)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.setStretch(3, 1)
        self.verticalLayout_3.setStretch(4, 1)
        self.horizontalLayout_2.addWidget(self.vertical, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.setStretch(0, 75)
        self.verticalLayout_4.addWidget(self.row_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow, row):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", row["CourseName"]))
        self.courseNameLabel.setText(_translate("MainWindow", row["CourseName"]))
        self.instructorLabel.setText(_translate("MainWindow", row["FullName"]))
        self.purchaseButton.setText(_translate("MainWindow", "Purchase"))
        self.descLabel.setText(_translate("MainWindow", row["Description"]))
        self.label.setText(_translate("MainWindow", "Difficulty"))
        self.diffLabel.setText(
            _translate("MainWindow", difficulties[row["Difficulty"]])
        )
        self.label_2.setText(_translate("MainWindow", "Duration"))
        self.durationLabel.setText(_translate("MainWindow", row["Duration"]))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
