from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centralwidget.sizePolicy().hasHeightForWidth()
        )
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 976, 1076))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth()
        )
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(20, 20, 30, 20)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_3.setSpacing(25)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.instructorNameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Avenir Next")
        font.setPointSize(72)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.instructorNameLabel.setFont(font)
        self.instructorNameLabel.setTextFormat(QtCore.Qt.AutoText)
        self.instructorNameLabel.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft
        )
        self.instructorNameLabel.setWordWrap(True)
        self.instructorNameLabel.setObjectName("instructorNameLabel")
        self.verticalLayout_3.addWidget(self.instructorNameLabel)
        self.row_job = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.row_job.sizePolicy().hasHeightForWidth())
        self.row_job.setSizePolicy(sizePolicy)
        self.row_job.setObjectName("row_job")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.row_job)
        self.horizontalLayout.setContentsMargins(12, -1, -1, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.row_job)
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.jobLabel = QtWidgets.QLabel(self.row_job)
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(36)
        self.jobLabel.setFont(font)
        self.jobLabel.setObjectName("jobLabel")
        self.horizontalLayout.addWidget(self.jobLabel)
        self.horizontalLayout.setStretch(0, 20)
        self.horizontalLayout.setStretch(1, 80)
        self.verticalLayout_3.addWidget(self.row_job)
        self.row_uni = QtWidgets.QHBoxLayout()
        self.row_uni.setContentsMargins(12, 0, 12, 12)
        self.row_uni.setSpacing(20)
        self.row_uni.setObjectName("row_uni")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.row_uni.addWidget(self.label_3)
        self.universityLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(36)
        self.universityLabel.setFont(font)
        self.universityLabel.setObjectName("universityLabel")
        self.row_uni.addWidget(self.universityLabel)
        self.row_uni.setStretch(0, 20)
        self.row_uni.setStretch(1, 80)
        self.verticalLayout_3.addLayout(self.row_uni)
        self.row_bio = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.row_bio.sizePolicy().hasHeightForWidth())
        self.row_bio.setSizePolicy(sizePolicy)
        self.row_bio.setObjectName("row_bio")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.row_bio)
        self.horizontalLayout_2.setContentsMargins(12, 25, 25, 25)
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.row_bio)
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.bioLabel = QtWidgets.QLabel(self.row_bio)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bioLabel.sizePolicy().hasHeightForWidth())
        self.bioLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Avenir")
        font.setPointSize(24)
        self.bioLabel.setFont(font)
        self.bioLabel.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignTop)
        self.bioLabel.setWordWrap(True)
        self.bioLabel.setIndent(0)
        self.bioLabel.setObjectName("bioLabel")
        self.horizontalLayout_2.addWidget(self.bioLabel)
        self.horizontalLayout_2.setStretch(1, 75)
        self.verticalLayout_3.addWidget(self.row_bio)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow, instructor):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Instructor Details"))
        self.instructorNameLabel.setText(
            _translate("MainWindow", instructor["FullName"])
        )
        self.label_2.setText(_translate("MainWindow", "PROFESSION"))
        self.jobLabel.setText(_translate("MainWindow", instructor["JobDesc"]))
        self.label_3.setText(_translate("MainWindow", "UNIVERSITY"))
        self.universityLabel.setText(_translate("MainWindow", instructor["University"]))
        self.label.setText(_translate("MainWindow", "ABOUT"))
        self.bioLabel.setText(_translate("MainWindow", instructor["Bio"]))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
