from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(205, 0, 566, 1156))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth()
        )
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setStyleSheet('font: 18pt "Calibri";')
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_5.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mainForm = QtWidgets.QWidget(self.verticalFrame)
        self.mainForm.setMinimumSize(QtCore.QSize(500, 0))
        self.mainForm.setObjectName("mainForm")
        self.mainFormLayout = QtWidgets.QVBoxLayout(self.mainForm)
        self.mainFormLayout.setSpacing(20)
        self.mainFormLayout.setObjectName("mainFormLayout")
        self.fullNamelabel = QtWidgets.QLabel(self.mainForm)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.fullNamelabel.sizePolicy().hasHeightForWidth()
        )
        self.fullNamelabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fullNamelabel.setFont(font)
        self.fullNamelabel.setObjectName("fullNamelabel")
        self.mainFormLayout.addWidget(self.fullNamelabel)
        self.fullNameLineEdit = QtWidgets.QLineEdit(self.mainForm)
        self.fullNameLineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.fullNameLineEdit.setMaxLength(30)
        self.fullNameLineEdit.setObjectName("fullNameLineEdit")
        self.mainFormLayout.addWidget(self.fullNameLineEdit)
        self.label = QtWidgets.QLabel(self.mainForm)
        self.label.setObjectName("label")
        self.mainFormLayout.addWidget(self.label)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.mainForm)
        self.usernameLineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.usernameLineEdit.setMaxLength(10)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.mainFormLayout.addWidget(self.usernameLineEdit)
        self.label_2 = QtWidgets.QLabel(self.mainForm)
        self.label_2.setObjectName("label_2")
        self.mainFormLayout.addWidget(self.label_2)
        self.emailLineEdit = QtWidgets.QLineEdit(self.mainForm)
        self.emailLineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.emailLineEdit.setMaxLength(50)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.mainFormLayout.addWidget(self.emailLineEdit)
        self.label_3 = QtWidgets.QLabel(self.mainForm)
        self.label_3.setObjectName("label_3")
        self.mainFormLayout.addWidget(self.label_3)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.mainForm)
        self.passwordLineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.passwordLineEdit.setMaxLength(50)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.mainFormLayout.addWidget(self.passwordLineEdit)
        self.label_4 = QtWidgets.QLabel(self.mainForm)
        self.label_4.setObjectName("label_4")
        self.mainFormLayout.addWidget(self.label_4)
        self.confirmLineEdit = QtWidgets.QLineEdit(self.mainForm)
        self.confirmLineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.confirmLineEdit.setMaxLength(50)
        self.confirmLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmLineEdit.setObjectName("confirmLineEdit")
        self.mainFormLayout.addWidget(self.confirmLineEdit)
        self.verticalLayout_5.addWidget(self.mainForm)
        self.instructorForm = QtWidgets.QWidget(self.verticalFrame)
        self.instructorForm.setMinimumSize(QtCore.QSize(500, 0))
        self.instructorForm.setObjectName("instructorForm")
        self.instructorFormlayout = QtWidgets.QVBoxLayout(self.instructorForm)
        self.instructorFormlayout.setSpacing(20)
        self.instructorFormlayout.setObjectName("instructorFormlayout")
        self.label_5 = QtWidgets.QLabel(self.instructorForm)
        self.label_5.setObjectName("label_5")
        self.instructorFormlayout.addWidget(self.label_5)
        self.jobLineEdit = QtWidgets.QLineEdit(self.instructorForm)
        self.jobLineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.jobLineEdit.setMaxLength(30)
        self.jobLineEdit.setObjectName("jobLineEdit")
        self.instructorFormlayout.addWidget(self.jobLineEdit)
        self.label_6 = QtWidgets.QLabel(self.instructorForm)
        self.label_6.setObjectName("label_6")
        self.instructorFormlayout.addWidget(self.label_6)
        self.universityLineEdit = QtWidgets.QLineEdit(self.instructorForm)
        self.universityLineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.universityLineEdit.setMaxLength(30)
        self.universityLineEdit.setObjectName("universityLineEdit")
        self.instructorFormlayout.addWidget(self.universityLineEdit)
        self.label_7 = QtWidgets.QLabel(self.instructorForm)
        self.label_7.setObjectName("label_7")
        self.instructorFormlayout.addWidget(self.label_7)
        self.bioTextEdit = QtWidgets.QTextEdit(self.instructorForm)
        self.bioTextEdit.setObjectName("bioTextEdit")
        self.instructorFormlayout.addWidget(self.bioTextEdit)
        self.verticalLayout_5.addWidget(self.instructorForm)
        self.button = QtWidgets.QWidget(self.verticalFrame)
        self.button.setObjectName("button")
        self.buttonLayout = QtWidgets.QVBoxLayout(self.button)
        self.buttonLayout.setSpacing(20)
        self.buttonLayout.setObjectName("buttonLayout")
        self.instructorCheckBox = QtWidgets.QCheckBox(self.button)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.instructorCheckBox.sizePolicy().hasHeightForWidth()
        )
        self.instructorCheckBox.setSizePolicy(sizePolicy)
        self.instructorCheckBox.setMinimumSize(QtCore.QSize(0, 40))
        self.instructorCheckBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.instructorCheckBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.instructorCheckBox.setIconSize(QtCore.QSize(64, 64))
        self.instructorCheckBox.setObjectName("instructorCheckBox")
        self.buttonLayout.addWidget(self.instructorCheckBox)
        self.signUpPushButton = QtWidgets.QPushButton(self.button)
        self.signUpPushButton.setMinimumSize(QtCore.QSize(150, 60))
        self.signUpPushButton.setObjectName("signUpPushButton")
        self.buttonLayout.addWidget(self.signUpPushButton, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addWidget(self.button)
        self.verticalLayout_3.addWidget(self.verticalFrame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionBack = QtWidgets.QAction(MainWindow)
        self.actionBack.setObjectName("actionBack")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sign up"))
        self.fullNamelabel.setText(_translate("MainWindow", "Full Name"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.label_2.setText(_translate("MainWindow", "Email"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.label_4.setText(_translate("MainWindow", "Confirm your password"))
        self.label_5.setText(_translate("MainWindow", "Job"))
        self.label_6.setText(_translate("MainWindow", "University"))
        self.label_7.setText(_translate("MainWindow", "Bio"))
        self.instructorCheckBox.setText(
            _translate("MainWindow", "Do you want to sign up as an instructor?")
        )
        self.signUpPushButton.setText(_translate("MainWindow", "Sign Up"))
        self.actionBack.setText(_translate("MainWindow", "Back"))
        self.actionBack.setToolTip(
            _translate("MainWindow", "Go back to previous screen")
        )
        self.actionBack.setShortcut(_translate("MainWindow", "Ctrl+B"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
